spring:
  application:
    name: product
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.0.1:8848
        ip: 172.18.0.1
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.18.0.1:3306/suimai_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    host: 172.18.0.1
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000  #10分钟
      #是否缓存空值，防止缓存穿透
      cache-null-values: true

mydef:
  sql:
    formatter:
      log: true

