server:
  port: 20000
spring:
  application:
    name: suimai-auth-server
  jackson:
    time-zone: GMT+08
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  redis:
    host: 127.0.0.1
    port: 6379
  thymeleaf:
    cache: false
