server:
  port: 8000

spring:
  application:
    name: member
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/suimai_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    time-zone: GMT+08


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
logging:
  level:
    com.atguigu.gulimall: debug