server:
  port: 30000
spring:
  application:
    name: suimai-third-party
  jackson:
    time-zone: GMT+08
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
    alicloud:
      access-key: LTAI5tEzhpiWWmnunSd5GnLK
      secret-key: hW6NxGfx9wKTT4tNWFTcoJybvUdOKA
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com