server:
  port: 30000
spring:
  application:
    name: suimai-third-party
  jackson:
    time-zone: GMT+08
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.0.1:8848
        ip: 172.18.0.1

